version: "{branch} (#{build})"

image:
  - Visual Studio 2017
  #- Visual Studio 2015

environment:
  matrix:
    - DEBUG: 1
      STANDALONE: 1
      WARNINGS: 1
    - DEBUG: 1
      STANDALONE: 1
      WARNINGS: 1
      WIN9X: 1
    - DEBUG: 1
      WARNINGS: 1

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
    environment:
      BOOSTDIR: C:\Libraries\boost_1_63_0
    build_script:
      - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
      - cd asio\src
      - nmake -f Makefile.msc
      - nmake -f Makefile.msc check
  -
    matrix:
      only:
        - image: Visual Studio 2017
    environment:
      BOOSTDIR: C:\Libraries\boost_1_69_0
    build_script:
      - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits"
      - dir "C:\Program Files (x86)\Microsoft SDKs\Windows"
      - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\Bin"
      - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1"
      - call "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\Bin\SetEnv.cmd" /x64
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      - cd asio\src
      - nmake -f Makefile.msc
      - nmake -f Makefile.msc check
